### ISSUE TITLE
turncli example wastes CPU while waiting.

### ISSUE THREAD

**Issue by vi** [sile/rusturn#2]
```
$ strace -cf target/debug/examples/turncli ...
...
# ALLOCATED: server=V4(104.131.203.210:3478)
Relay address is Some(V4(104.131.203.210:62901))
# CHANNEL BOUND: peer=V4(93.84.76.218:24636)
...

% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 74.01    2.685272          20    132890           epoll_wait
 18.82    0.682884          20     33833         1 nanosleep
  7.17    0.260000       11818        22           futex
  0.00    0.000000           0        18           read
  0.00    0.000000           0        45           write
...
```

**Comment by vi** [comment]
Looks like it's `fibers` problems:

* https://github.com/dwango/fibers-rs/blob/84b09e4f003016c0794a84e71e47b8e0dd5d7aca/src/executor/thread_pool.rs#L105
* https://github.com/dwango/fibers-rs/blob/84b09e4f003016c0794a84e71e47b8e0dd5d7aca/src/executor/in_place.rs#L71

**Comment by sile** [comment]
Yes, you're right. It's a known problem of `fibers`. I'd like to consider how to deal with this issue at https://github.com/dwango/fibers-rs/issues/11.
Apart from that, I added `thread-count` option with the default value `1` to `turncli` example for mitigating this issue (commit: https://github.com/sile/rusturn/commit/aa2d507905256a8af0eeb8c78925003e3a396e10).
