### ISSUE TITLE
Using rusturn in synchronous context

### ISSUE THREAD

**Issue by marcbrevoort-cyberhive** [sile/rusturn#9]
Hello, I'm trying to use Rusturn in a synchronous context. This seems to work fine for creating the TURN client, however I'm having trouble with permissions creation.
if I observe network traffic on Wireshark, I see it send the first permission, and a response comes in in reply. However the second permission I try create for a different IP seems to hang.

I have tried both fibers_global::execute() and a loop of the following form,

```
use futures::Future;
let mut myasyncresult = turnclient.create_permission(peer.clone());
loop {
    std::thread::sleep(std::time::Duration::from_millis(100));
    match myasyncresult.poll() {
        Ok(futures::Async::NotReady) => {
            println!("poll: notready");
        }
        Ok(futures::Async::Ready(x)) => {
            println!("poll: ready: {:?}", x);
            break;
        }
        Err(e) => {
            println!("poll: err, e={:?}", e);
            break;
        }
    }
};
````
and this shows that once the message has been sent out, the asyncresult forever sits there printing "poll: notready", which would explain the second request not going out. Could you suggest what things I've missed might cause the incoming response data never to be processed?

**Comment by marcbrevoort-cyberhive** [comment]
Adding `turnclient.poll_send();` and `turnclient.poll_recv();` fixed it. I would've called `wait` but it demands ownership of the client, so it's not usable in a context where the client might be kept in a struct (and hence only a reference to the client is available).
Also since the library doesn't seem to be thread-safe, I've had to add a lock to the client.

**Comment by sile** [comment]
I'm glad you were able to resolve it yourself 👍 
(And sorry for lack of documentation)
